---
admin:
  deploy: true
  concurrency: 5
  gunicornProcesses: 5
  gunicornThreads: 1
  namespace: babylon
  image: quay.io/redhat-cop/babylon-admin:latest
  oauthProxyImage: openshift/oauth-proxy:latest
  redisImage: image-registry.openshift-image-registry.svc:5000/openshift/redis:5-el8
  redisPassword: generate

anarchy:
  apiGroup: anarchy.gpte.redhat.com
  namespace: anarchy
  serviceAccountName: anarchy
  defaultRunnerServiceAccountName: anarchy-runner-default

poolboy:
  apiGroup: poolboy.gpte.redhat.com
  namespace: poolboy

catalogNamespaces: []

crossClusterBackup:
  enable: false
  clusterRoleName: babylon-cross-cluster-backup
  namespace: babylon-cross-cluster-backup
  #kubeConfig: ...


anarchy-operator:
  enabled: true
  # any values from the anarchy-operator chart
  # that you may wish to provide a better default
  # for

agnosticv-operator:
  enabled: true
  # any values from the agnosticv-operator chart
  # that you may wish to provide a better default
  # for

poolboy-operator:
  enabled: true
  # any values from the poolboy-operator chart
  # that you may wish to provide a better default
  # for
